### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 6185: illegal multibyte sequence

### ISSUE THREAD

**Issue by fengyao321** [DexterZeng/CEA#1]
i downloaded  name_vec.txt.
but i encountered this problem. 
can you help me?

**Comment by DexterZeng** [comment]
Hi, thanks for your interest in our work. The codes are based on Linux system. I guess this error takes place under the Windows system? In such case, you might want to change the loading of files to:
```
inf = open(path, "r", encoding="utf-8")
```

**Comment by fengyao321** [comment]
Thank you very much. Now i have adressed this problem.



---Original---
From: "Weixin ***@***.***&gt;
Date: Wed, Aug 11, 2021 15:38 PM
To: ***@***.***&gt;;
Cc: "Feng ***@***.******@***.***&gt;;
Subject: Re: [DexterZeng/CEA] UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 6185: illegal multibyte sequence (#1)




 
Hi, thanks for your interest in our work. The codes are based on Linux system. I guess this error takes place under the Windows system? In such case, you might want to change the loading of files to:
 inf = open(path, "r", encoding="utf-8")  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
